<?php
/* Magedelight
 * Copyright (C) 2016 Magedelight <info@magedelight.com>
 *
 * NOTICE OF LICENSE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://opensource.org/licenses/gpl-3.0.html.
 *
 * @category Magedelight
 * @package Magedelight_Giftcard
 * @copyright Copyright (c) 2016 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */

if ($block->isGiftcardProduct()){
    if($block->getItemsData()){
        $itemData = $block->getItemsData();
    }
    $product = $block->getCurrentProduct();
    $giftcardType = $product->getData('giftcard_price_type');
    ?>

    <div id="modal-form">
       
    </div>
    <script type="text/x-magento-init">
        {
            ".open-modal-form": {
                "Magedelight_Giftcard/js/form": {}
            }
        }
    </script>
    
    <script type="text/javascript">
        require(
        [
            'jquery',
            'Magento_Catalog/js/price-utils'
        ],
            function ($,priceUtils) {
                "use strict";
                
                function sendFriendToggle(){
                    if ($('#send_friend').is(':checked')) {
                        //$('#giftvoucher-receiver').show();
                    }
                    else{
                        //$('#giftvoucher-receiver').hide();
                    }
                    if ($('#recipient_ship').is(':checked')) {
                        $('#recipient_ship_desc').show();
                    }
                    else{
                        $('#recipient_ship_desc').hide();
                    }
                }
                
                $(document).ready(function(){
                    sendFriendToggle();
                    $('#send_friend').change(function(){
                        sendFriendToggle();
                    });
                    
                    $('#recipient_ship').change(function(){
                        sendFriendToggle();
                    });
                    updateImage();
                    
                    $('#price').keyup(function(){                        
                        updatePrice(this);
                    });
                });
                $(window).load(function(){
                    $('.price-wrapper .price').html($('#price').attr('data-format-val'));
                    updatePrice($('#price')[0]);
                });
                
                function updatePrice(obj){
                    var price = $(obj).val();
                    if($.isNumeric(price)){
                        price = priceUtils.formatPrice(price);
                        $('.price-wrapper .price').html(price);
                    }
                }
                
                function updateImage(){
                    setTimeout(function(){
                        var url = $('.fotorama__stage__frame[data-active=true]').attr('href')
                        $('#imageurl').val(url);
                        updateImage();
                    },1000);
                }                
            }
        );
    </script>
    
    <?php
    $price = '';
    if(isset($itemData['price']) && !empty($itemData['price'])){
        $price = $itemData['price'];
    }
    ?>
    <?php
    if ($giftcardType == 2){
        $giftcardType = $product->getData('giftcard_price_type');
        $giftcardMinPrice = $product->getData('giftcard_price_min');
        $giftcardMaxPrice = $product->getData('giftcard_price_max');
        ?>
        <div class="giftvoucherprice-box">
            <div class="form-group">
                <label for="price">Price</label>         
                <label for="validity_form" data-value="<?php echo $block->getLifeTime(); ?>" class="validity_form">
                    Validity :- <?php echo $block->getLifeTime(); ?>
                </label>
                <input type="text" maxlength="30" value="<?php echo $price; ?>" id="price" name="additional_options[price]" class="giftvoucher_custom_option input-text required-entry form-control validate-greater-than-zero validate-digits-range digits-range-<?php echo $giftcardMinPrice; ?>-<?php echo $giftcardMaxPrice; ?>" />
                (
                <span class="price">
                    <span class="price"><?php echo $block->getFormattedPrice($product->getData('giftcard_price_min')); ?></span>
                </span>
                -
                <span class="price">
                    <span class="price"><?php echo $block->getFormattedPrice($product->getData('giftcard_price_max')); ?></span>
                </span>
                )
            </div>
        </div>
        <?php
    }else{
        ?>
        <input type="hidden" maxlength="30" data-format-val="<?php echo $block->getFormattedPriceContainer($product->getData('giftcard_balance')); ?>" value="<?php echo $product->getData('giftcard_balance'); ?>" id="price" name="additional_options[price]" class="hiddenprice input-text required-entry validate-greater-than-zero" />        
        <div class="giftvoucherprice-box">
            <div class="form-group">
                <label for="validity_form" data-value="<?php echo $block->getLifeTime(); ?>" class="validity_form">
                    Validity :- <?php echo $block->getLifeTime(); ?>
                </label>
            </div>
        </div>        
        <?php
    }
    ?>
    <div class="giftvoucher-product-info gift-card">
        <div class="recipient-ship-form-box">
        <div class="giftcard-send-friend form-group">
            <?php
            $send_friend = '';
            if(isset($itemData['send_friend']) && $itemData['send_friend'] == 1){
                $send_friend = "checked";
            }
            ?>
            <div class="checkbox">
                <label for="send_friend"><input type="checkbox" <?php echo $send_friend; ?> id="send_friend" name="additional_options[send_friend]" value="1" class="giftvoucher_custom_option">Send Gift Card Online</label>
            </div>
        </div>
            <?php
            $recipient_ship = '';
            if(isset($itemData['recipient_ship']) && $itemData['recipient_ship'] == 1){
                $recipient_ship = "checked";
            }
            ?>
        <div class="recipient_ship_form form-group">
            <div class="checkbox">
                <label for="recipient_ship" class="recipient_ship">
                    <input type="checkbox" id="recipient_ship" name="additional_options[recipient_ship]" <?php echo $recipient_ship; ?> value="1" class="giftvoucher_custom_option">Send through post office
                </label>
            </div>
            <div id="recipient_ship_desc" class="form-group">
                You need to fill in your friend's address as the shipping address on checkout page. We will send this Gift Card to that address.
            </div>
        </div>
        </div>

        <div id="giftvoucher-receiver" class="giftvoucher-receiver form-group">
            <?php
            $customer_name = '';
            if(isset($itemData['customer_name']) && !empty($itemData['customer_name'])){
                $customer_name = $itemData['customer_name'];
            }
            ?>
            <div class="form-group name">
                <label for="customer_name">Sender name (optional)</label>
                <input type="text" maxlength="30" value="<?php echo $customer_name; ?>" id="customer_name" name="additional_options[customer_name]" class="giftvoucher_custom_option input-text form-control">
            </div>
            <?php
            $recipient_name = '';
            if(isset($itemData['recipient_name']) && !empty($itemData['recipient_name'])){
                $recipient_name = $itemData['recipient_name'];
            }
            ?>
            <div class="form-group name1">
                <label for="recipient_name">Recipient name<em>*</em></label>
                <input type="text" maxlength="30" value="<?php echo $recipient_name; ?>" id="recipient_name" name="additional_options[recipient_name]" class="giftvoucher_custom_option input-text required-entry form-control" data-validate="{required:true}">
            </div>
            <?php
            $recipient_email = '';
            if(isset($itemData['recipient_email']) && !empty($itemData['recipient_email'])){
                $recipient_email = $itemData['recipient_email'];
            }
            ?>
            <div class="form-group email">
                <label for="recipient_email" class="recipient_email">Recipient email address<em>*</em></label>
                <input type="text" value="<?php echo $recipient_email; ?>" id="recipient_email" name="additional_options[recipient_email]" class="giftvoucher_custom_option input-text required-entry validate-email validate-same-email form-control" data-validate="{required:true}">
            </div>
            <?php
            $message = '';
            if(isset($itemData['message']) && !empty($itemData['message'])){
               $message = $itemData['message'];
            }
            ?>
            <div class="form-group message">
                <label for="message" class="message">Message</label>
                <textarea id="message" name="additional_options[message]" class="form-control" maxlength="220"><?php echo $message; ?></textarea>               
            </div>            
        </div>
        <div id="giftvoucher-receiver" class="giftvoucher-button-box">
        <button class="button btn-cart action open-modal-form" id="giftcard-preview-button-add" title="Preview template" type="button">
            <span>
                <span>Preview Gift Card</span>
            </span>
        </button>
        <?php
        $imageurl = $block->getGiftImageUrl();
        if(isset($itemData['imageurl']) && !empty($itemData['imageurl'])){
           $imageurl = $itemData['imageurl'];
        }
        ?>
        <input type="hidden" value="<?php echo $imageurl; ?>" id="imageurl" name="additional_options[imageurl]" class="input-text" />
        </div>
    </div>
    <?php
}
?>